CREATE TABLE `beiker_unionpage_keyword` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关键词ID',
	`keyword` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '关键词',
	`addtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatetime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`isused` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否使用 0：使用；1：删除',
	PRIMARY KEY (`id`),
	INDEX `keyword_index` (`keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='静态聚合页面关键词' AUTO_INCREMENT=100000;
